### ISSUE TITLE
no redirection after deconnection

### ISSUE THREAD

**Issue by pierrealexaline** [cmsimple-xh/memberpages#18]
The pluggin don't make the reddirection after deconnection...I have created a deconnection hidding page, and when i deconnect, i cannot go to that pageeven if i make that page visible.

**Comment by cmb69** [comment]
Hmm, did you enter the name of the page here (not necessarily en.php, but your language): https://github.com/cmsimple-xh/memberpages/blob/ac981ab876814f2951f54834e8b1c4bf81edfa3a/languages/en.php#L5
It shouldn't matter whether that page is visible; it actually does not matter if the page exists at all.

PS: relevant code: https://github.com/cmsimple-xh/memberpages/blob/2b6b4e7aa83159255e8d05b470f3582acc45efea/index.php#L94-L99

**Comment by pierrealexaline** [comment]
Ok nice....i close this issue....that's work great.
