### ISSUE TITLE
Nested ternary operator raises fatal error in PHP 8

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/memberpages#19]
There is an [assignment to `$newpw_too_simple`](https://github.com/cmsimple-xh/memberpages/blob/2b6b4e7aa83159255e8d05b470f3582acc45efea/index.php#L888-L894) which uses unparenthesized nested ternary operators, and as such triggers deprecated warnings with PHP 7.4. On a cursory glance, this looks like a bug (namely, assuming right associativity of the ternary operator).

**Comment by cmb69** [comment]
Well, in this case it doesn't matter whether the ternary operator is left or right associative; result is the same. So assuming right-assiciativity, refactoring yields the IMO slightly clearer:
````.php
$newpw_too_simple  = $newpassword && $pwextra
    && ($pwextra== 1 && !preg_match('!^.*(?=.*[\p{Lu}]).*(?=.*[\p{Ll}]).*$!u',$newpassword)
        || $pwextra == 2 && !preg_match('!^.*(?=.*[\p{Lu}]).*(?=.*[\p{Ll}]).*(?=.*[\p{N}]).*$!u',$newpassword));
````

**Comment by lck-git** [comment]
> Well, in this case it doesn't matter whether the ternary operator is left or right associative; result is the same. So assuming right-assiciativity, refactoring yields the IMO slightly clearer:
> 
> ```hack
> $newpw_too_simple  = $newpassword && $pwextra
>     && ($pwextra== 1 && !preg_match('!^.*(?=.*[\p{Lu}]).*(?=.*[\p{Ll}]).*$!u',$newpassword)
>         || $pwextra == 2 && !preg_match('!^.*(?=.*[\p{Lu}]).*(?=.*[\p{Ll}]).*(?=.*[\p{N}]).*$!u',$newpassword)));
> ```

Da ist eine Klammer zu viel am Ende, bei `$newpassword)));`

**Comment by cmb69** [comment]
> Da ist eine Klammer zu viel am Ende, bei `$newpassword)));`

Jetzt gefixt. (Besser spät als nie :)
