### ISSUE TITLE
PHP 8.x - Uncaught Error & Uncaught TypeError (funcs.php)

### ISSUE THREAD

**Issue by lck-git** [cmsimple-xh/memberpages#20]
More detailed info and possible fix, see: https://cmsimpleforum.com/viewtopic.php?f=16&t=18964&p=85364#p85364

**Comment by cmb69** [comment]
Indeed, the `create_function()` issue happens when a new member is added, and the config option `generate_password` is not equal to zero.

And the `mktime()` issue happens when saving an empty expirement date (so requires the config option `show_expires` to be enabled).
