### ISSUE TITLE
Instead of list of active members the home page is shown

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/memberpages#4]
Due to cmsimple-xh/cmsimple-xh#21 [`$memberlist_ajax`](https://github.com/cmsimple-xh/memberpages/blob/29d2868c0b109951fe8f161de489501084358335/memberlist.php#L308) isn't automatically imported anymore.

**Comment by ojaybs** [comment]
Display of the memberlist is working now: [https://cmsimpleforum.com/viewtopic.php?f=2&t=12885&p=61163#p61163](https://cmsimpleforum.com/viewtopic.php?f=2&t=12885&p=61163#p61163)
